config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :posts do 
  	resources :comments
  end

  root "posts#index"

  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	# Maind page showing added post
	def index
		@post = Post.all.order('created_at DESC')
	end
	# Redirection to New Post page
	def new
		@post  = Post.new
	end
	# Creating new post
	def create 
		@post  = Post.new(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end
	#showing created post
	def show
		@post = Post.find(params[:id])
	end
	# editing created post
	def edit
		@post = Post.find(params[:id])
	end
	# Updating edited post
	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end
	# deleting created post
	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to root_path
	end

	private
		def post_params
			params.require(:post).permit(:title, :body)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> ago</p>
	</div>

	<p><%= link_to 'Delete', [comment.post, comment],
					method: :delete,
					class: "button",
					data: { confirm: 'Are you sure you want to delete this comment?'}%>					
	</p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>	
		<%= f.label :name %><br>
		<%= f.text_field :name %><br>
	</p>
	<p>	
		<%= f.label :body %><br>
		<%= f.text_area :body %><br>
	</p>
	<br>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
  	<div id="sidebar">	
	  	<div id="logo">
		  	<h2 style="color: #00B9AE;"><b>Blog</b></h2>
	  	</div>

	  	<ul>
			<li class="category">Website</li>
			<li><%= link_to "Blog", root_path %></li>
			<li><%= link_to "About", about_path %></li>
		</ul>

		<ul>
			<li class="category">Social</li>
			<li><a href="https://www.facebook.com/Helias21">Facebook</a></li>
			<li><a href="https://www.youtube.com/channel/UCTfOGLzR0b8J8jQ45p5HCWw">Youtube</a></li>
			<li><a href="https://gitlab.com/epamintuan32">Git</a></li>
			<li></li>
		</ul>
  	</div>

  	<div id="main_content">
  		<div id="header">
      <% if current_page?(root_path) %>
        <p>All Posts</p>
      <% elsif current_page?(about_path) %>
        <p>About</p>
      <% else %>
        <%= link_to "<- Back to Main Page", root_path %>
      <% end %>

  			<div class="buttons">
  				<button class="button">
					<%= link_to "New Post", new_post_path %>
  				</button>
  			</div>
  		</div>
  		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class:"alert") %>
  		<% end %>
  		 <%= yield %>
  	</div>
	
   
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "logo.jpg", class: "about_img" %>
	</div>

	<div id="content">
		<h1>Elijah Pamintuan</h1>
		<p>I'm an otaku person. I love animes and stuff. I even go to conventions with my friends and have a lot fun.</p>
		<p>I also do streams on weekends because I love playing "Monster Hunter world". Sommtimes I also party up with my friends in Dota2. In short, I have a heart of a gamer.</p>


	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> not valid for saving</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg|%>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %><br>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %><br>
	</p>

	<p>
		<%= f.submit %><br>
	</p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Posts</h1>

	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @post.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title">
			<%= link_to post.title, post %>
		</h2>
		<p class="date">
			<%= post.created_at.strftime("%B, %d, %Y") %>
		</p>
	</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>New Posts</h1>

	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title">
	<%= @post.title %>
	</h1>

	<p class="date">
		Submitted <%= time_ago_in_words(@post.created_at) %> ago
		| <%= link_to 'Edit', edit_post_path(@post) %> 
		| <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure you want to permanently delete this post?' } %>
	</p>

	<p class="body">
		<%= @post.body %>
	</p>	

	<div id="comment">
		<h2>
			<%= @post.comments.count %> Comments
		</h2>
		<%= render @post.comments %>

		<h3>
			Add Comment
		</h3>
		<%= render "comments/form" %>	
	</div>
</div>